version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: cms
    restart: unless-stopped
    networks:
      - cms-app-network
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: cmsDB
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: cms_user
      DATABASE_PASSWORD: cms_pass
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: cmsDB
    networks:
      - cms-app-network
    environment:
      POSTGRES_DB: cmsDB
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: cms_pass
    volumes:
      - cmsdata:/var/lib/postgresql/data

networks:
  cms-app-network:
    driver: bridge

volumes:
  cmsdata:
